In [2]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd


#abrir el csv /Users/maria/Documents/Business Intehlligence/datasets/AtencionesUrgencia2024.csv para explorar los datos y hacer un análisis de los mismos.
with open('/Users/maria/Documents/Business Intehlligence/datasets/AtencionesUrgencia2024.csv', 'r') as file:
    # Leer el archivo CSV en un DataFrame de pandas
    file.close()
    df = pd.read_csv(file.name, sep=';', encoding='cp1252')

df.head()  # Mostrar las primeras filas del DataFrame para explorar los datos

/var/folders/4r/bv24jr955x9g3b9fjjv0bm_c0000gn/T/ipykernel_31005/2901334567.py:11: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file.name, sep=';', encoding='cp1252')

,IdEstablecimiento,NEstablecimiento,IdCausa,GlosaCausa,Total,Menores_1,De_1_a_4,De_5_a_14,De_15_a_64,De_65_y_mas,...,semana,GLOSATIPOESTABLECIMIENTO,GLOSATIPOATENCION,GlosaTipoCampana,CodigoRegion,NombreRegion,CodigoDependencia,NombreDependencia,CodigoComuna,NombreComuna
0,01-100,Hospital Regional Dr. Juan Noé Crevani (Arica),29,DIARREA AGUDA (A00-A09),16,2,4,5,3,2,...,1,Hospital,Indiferenciado,Ninguna,15.0,De Arica y Parinacota,1.0,Arica,15101.0,Arica
1,01-100,Hospital Regional Dr. Juan Noé Crevani (Arica),21,TOTAL DEMÁS CAUSAS,148,5,6,19,95,23,...,1,Hospital,Indiferenciado,Ninguna,15.0,De Arica y Parinacota,1.0,Arica,15101.0,Arica
2,01-100,Hospital Regional Dr. Juan Noé Crevani (Arica),25,SECCIÓN 2. TOTAL DE HOSPITALIZACIONES,26,0,1,2,16,7,...,1,Hospital,Indiferenciado,Ninguna,15.0,De Arica y Parinacota,1.0,Arica,15101.0,Arica
3,01-100,Hospital Regional Dr. Juan Noé Crevani (Arica),7,CAUSAS SISTEMA RESPIRATORIO,2,0,0,0,1,1,...,1,Hospital,Indiferenciado,Ninguna,15.0,De Arica y Parinacota,1.0,Arica,15101.0,Arica
4,01-100,Hospital Regional Dr. Juan Noé Crevani (Arica),33,"- COVID-19, VIRUS NO IDENTIFICADO U07.2",0,0,0,0,0,0,...,1,Hospital,Indiferenciado,Ninguna,15.0,De Arica y Parinacota,1.0,Arica,15101.0,Arica

In [13]:
#limpieza de valores nulos 
df.isnull().sum()  # Contar los valores nulos en cada columna
df_limpio = df.dropna(inplace=True)  # Eliminar filas con valores nulos

In [16]:
#numero total de filas y columnas
# Crear el DataFrame limpio y mostrar sus dimensiones
df_limpio = df.dropna()
df_limpio.shape

(8921589, 22)

In [17]:
#todas las columnas del dataset
df_limpio.columns  # Mostrar todas las columnas del DataFrame

Index(['IdEstablecimiento', 'NEstablecimiento', 'IdCausa', 'GlosaCausa',
       'Total', 'Menores_1', 'De_1_a_4', 'De_5_a_14', 'De_15_a_64',
       'De_65_y_mas', 'fecha', 'semana', 'GLOSATIPOESTABLECIMIENTO',
       'GLOSATIPOATENCION', 'GlosaTipoCampana', 'CodigoRegion', 'NombreRegion',
       'CodigoDependencia', 'NombreDependencia', 'CodigoComuna',
       'NombreComuna', 'Total_Personas_Atendidas'],
      dtype='object')

In [25]:
#Menores_1	De_1_a_4	De_5_a_14	De_15_a_64	De_65_y_mas

#sumar todas las filas por cada columna para obtener el total de personas atendidas en urgencias por rango de edad.
total_personas = df_limpio[['Menores_1', 'De_1_a_4', 'De_5_a_14', 'De_15_a_64', 'De_65_y_mas']].sum()
print(total_personas)  # Mostrar el total de personas atendidas en urgencias por rango de edad

Menores_1       1669228
De_1_a_4        5770134
De_5_a_14      11978111
De_15_a_64     39929871
De_65_y_mas    10144568
dtype: int64

In [34]:
#diagnosticos más frecuentes
#hay una columna de idCausa que contiene el codigo del diagnostio, y en la fila del diagnostico se encuentra la cantidad de personas atendidas por rango etario y un total de personas con ese diagnostico.

diagnosticos_frecuentes = (
    df_limpio
    .groupby(['IdCausa', 'GlosaCausa'], as_index=False)['Total_Personas_Atendidas']
    .sum()
    .sort_values('Total_Personas_Atendidas', ascending=False)
)

diagnosticos_frecuentes
print(diagnosticos_frecuentes)  # Mostrar los diagnosticos más frecuentes y la cantidad de personas atendidas por cada uno

    IdCausa                                         GlosaCausa  \
31       34                                      TOTAL DEMANDA
0         1            SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA
19       21                                 TOTAL DEMÁS CAUSAS
1         2                  TOTAL CAUSAS SISTEMA RESPIRATORIO
8        10                                 IRA Alta (J00-J06)
16       18                TOTAL TRAUMATISMOS Y ENVENENAMIENTO
18       20                              Otras causas externas
2         3           Bronquitis/bronquiolitis aguda (J20-J21)
26       29                            DIARREA AGUDA (A00-A09)
23       25              SECCIÓN 2. TOTAL DE HOSPITALIZACIONES
10       12                  TOTAL CAUSAS SISTEMA CIRCULATORIO
7         8                                 - LAS DEMÁS CAUSAS
5         6  Otra causa respiratoria (J22, J30-J39, J47, J6...
33       36      TOTAL CAUSAS DE TRASTORNOS MENTALES (F00-F99)
4         5                                 Neumonía (J12-J18)
9        11             Crisis obstructiva bronquial (J40-J46)
15       17                         Otras causas circulatorias
37       40  Trastornos neuróticos, trastornos relacionados...
17       19                            Accidentes del tránsito
3         4                                Influenza (J09-J11)
13       15                                Crisis hipertensiva
6         7                        CAUSAS SISTEMA RESPIRATORIO
22       24                               CIRUGÍAS DE URGENCIA
20       22                      - CAUSAS SISTEMA CIRCULATORIO
21       23                   - TRAUMATISMOS Y ENVENENAMIENTOS
38       41  Otros trastornos mentales no contenidos en las...
12       14                      Accidente vascular encefálico
14       16                                     Arritmia grave
27       30                 Covid-19, Virus identificado U07.1
36       39         Trastornos del Humor (Afectivos) (F30-F39)
35       38  Trastornos mentales y del comportamiento debid...
39       42         - CAUSAS POR TRASTORNOS MENTALES (F00-F99)
11       13                            Infarto agudo miocardio
28       31              Covid-19, Virus no identificado U07.2
34       37                           Ideación Suicida (R45.8)
32       35  Lesiones autoinfligidas intencionalmente (X60-...
30       33            - COVID-19, VIRUS NO IDENTIFICADO U07.2
29       32               - COVID-19, VIRUS IDENTIFICADO U07.1
24       27             Pacientes en espera de hospitalización
25       28  Pacientes en espera de hospitalización que esp...

    Total_Personas_Atendidas
31                  21237302
0                   19294260
19                  10227492
1                    5500158
8                    3725977
16                   2117146
18                   1953725
2                     831647
26                    696046
23                    633303
10                    398338
7                     370257
5                     355778
33                    303106
4                     264183
9                     198342
15                    195367
37                    172146
17                    153776
3                     124231
13                     98716
6                      89170
22                     80722
20                     74196
21                     70732
38                     59567
12                     46815
14                     34773
27                     30745
36                     30500
35                     28463
39                     27306
11                     22667
28                     21239
34                     12430
32                      9649
30                       896
29                       746
24                         0
25                         0

In [33]:
#cantidad de IdCausa únicos y sus nombres de diagnosticos asociados
cantidad_id_causa_unicos = df_limpio['IdCausa'].nunique()
print(f'Cantidad de IdCausa únicos: {cantidad_id_causa_unicos}')

# Obtener los nombres de los diagnosticos asociados a cada IdCausa único
nombres_diagnosticos = df_limpio[['IdCausa', 'GlosaCausa']].drop_duplicates()
print('\nNombres de diagnosticos asociados:')
print(nombres_diagnosticos)

Cantidad de IdCausa únicos: 40

Nombres de diagnosticos asociados:
    IdCausa                                         GlosaCausa
0        29                            DIARREA AGUDA (A00-A09)
1        21                                 TOTAL DEMÁS CAUSAS
2        25              SECCIÓN 2. TOTAL DE HOSPITALIZACIONES
3         7                        CAUSAS SISTEMA RESPIRATORIO
4        33            - COVID-19, VIRUS NO IDENTIFICADO U07.2
5        32               - COVID-19, VIRUS IDENTIFICADO U07.1
6        22                      - CAUSAS SISTEMA CIRCULATORIO
7        23                   - TRAUMATISMOS Y ENVENENAMIENTOS
8        42         - CAUSAS POR TRASTORNOS MENTALES (F00-F99)
9        24                               CIRUGÍAS DE URGENCIA
10        8                                 - LAS DEMÁS CAUSAS
11       27             Pacientes en espera de hospitalización
12       28  Pacientes en espera de hospitalización que esp...
13       40  Trastornos neuróticos, trastornos relacionados...
14       41  Otros trastornos mentales no contenidos en las...
26       16                                     Arritmia grave
27       17                         Otras causas circulatorias
28       18                TOTAL TRAUMATISMOS Y ENVENENAMIENTO
29       19                            Accidentes del tránsito
30       35  Lesiones autoinfligidas intencionalmente (X60-...
31       20                              Otras causas externas
32       36      TOTAL CAUSAS DE TRASTORNOS MENTALES (F00-F99)
33       37                           Ideación Suicida (R45.8)
34       38  Trastornos mentales y del comportamiento debid...
35       39         Trastornos del Humor (Afectivos) (F30-F39)
43        6  Otra causa respiratoria (J22, J30-J39, J47, J6...
44       31              Covid-19, Virus no identificado U07.2
45       30                 Covid-19, Virus identificado U07.1
46       12                  TOTAL CAUSAS SISTEMA CIRCULATORIO
47       13                            Infarto agudo miocardio
48       14                      Accidente vascular encefálico
49       15                                Crisis hipertensiva
83       34                                      TOTAL DEMANDA
84        1            SECCIÓN 1. TOTAL ATENCIONES DE URGENCIA
85        2                  TOTAL CAUSAS SISTEMA RESPIRATORIO
86       10                                 IRA Alta (J00-J06)
87        4                                Influenza (J09-J11)
88        5                                 Neumonía (J12-J18)
95        3           Bronquitis/bronquiolitis aguda (J20-J21)
96       11             Crisis obstructiva bronquial (J40-J46)

In [4]:
#abrir grd parquet para explorar los datos y hacer un análisis de los mismos.
grd_parquet = pd.read_parquet('/Users/maria/Documents/Business Intehlligence/datasets/grd_procesado.parquet')
grd_parquet.head()  # Mostrar las primeras filas del DataFrame para explorar los datos

,COD_ESTABLECIMIENTO,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,PROVINCIA,COMUNA_REGISTRADA,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,...,CAMAS_CRITICAS,POB_MULT_ESTAB,COMUNA_CON_ESTAB_AC,FALLECIDO,CRITICAS_PROP,CAMAS_COMUNA,CRITICAS_COMUNA,CAMAS_1000HAB,CRITICAS_1000HAB,TASA_MORTALIDAD_COMUNA
0,118100,467373,HOMBRE,1969-09-10,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) B,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
1,118100,562854,HOMBRE,1956-02-07,CONCEPCION,CORONEL,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963
2,118100,199980,MUJER,1960-02-28,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,APS CONSULTORIO (CESFAM),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
3,118100,857926,MUJER,1933-01-12,CONCEPCION,CHIGUAYANTE,FONASA INSTITUCIONAL - (MAI) D,CONCEPCIÓN,"OTRAS INSTITUCIONES SALUD (CLÍNICAS PRIVADAS, ...",URGENCIA,...,113,0.090303,0,1,0.128118,882,113,3.717488,0.476277,0.117963
4,118100,284629,HOMBRE,1951-05-03,CURICO,TENO,FONASA INSTITUCIONAL - (MAI) C,DEL MAULE,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963

In [11]:
#valores nulos en el parquet
grd_parquet.isnull().sum()  # Contar los valores nulos en cada columna del DataFrame parquet

COD_ESTABLECIMIENTO          0
CIP_ENCRIPTADO               0
SEXO                         0
FECHA_NACIMIENTO             0
PROVINCIA                    0
COMUNA_REGISTRADA            0
PREVISION                    0
SERVICIO_SALUD               0
TIPO_PROCEDENCIA             0
TIPO_INGRESO                 0
FECHA_INGRESO                0
FECHAALTA                    0
TIPOALTA                     0
DIAGNOSTICO1                 0
DIAGNOSTICO2                 9
DIAGNOSTICO3              4920
PROCEDIMIENTO1             127
PROCEDIMIENTO2            2329
IR_29301_COD_GRD             0
IR_29301_PESO                0
IR_29301_SEVERIDAD           0
IR_29301_MORTALIDAD          0
YEAR                         0
EDAD                         0
DIAS_ESTANCIA                0
N_COMORBILIDADES             0
N_PROCEDIMIENTOS             0
INDICE_CHARLSON              0
DESCRIPCION                  0
SECCION                      0
COD_REGION                   0
REGION                       0
ESTABLECIMIENTO              0
COD_COMUNA                   0
COMUNA_ESTAB                 0
LATITUD                      0
LONGITUD                     0
PRESTADOR                    0
COMPLEJIDAD_ESTAB            0
POB_COMUNA                   0
POB_REGION                   0
CAMAS_TOTALES                0
CAMAS_CRITICAS               0
POB_MULT_ESTAB               0
COMUNA_CON_ESTAB_AC          0
FALLECIDO                    0
CRITICAS_PROP                0
CAMAS_COMUNA                 0
CRITICAS_COMUNA              0
CAMAS_1000HAB                0
CRITICAS_1000HAB             0
TASA_MORTALIDAD_COMUNA       0
dtype: int64

In [9]:
grd_femenino = grd_parquet[grd_parquet['SEXO'] == 'MUJER']
grd_femenino.head()  # Mostrar las primeras filas del DataFrame filtrado por sexo femenino

,COD_ESTABLECIMIENTO,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,PROVINCIA,COMUNA_REGISTRADA,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,...,CAMAS_CRITICAS,POB_MULT_ESTAB,COMUNA_CON_ESTAB_AC,FALLECIDO,CRITICAS_PROP,CAMAS_COMUNA,CRITICAS_COMUNA,CAMAS_1000HAB,CRITICAS_1000HAB,TASA_MORTALIDAD_COMUNA
2,118100,199980,MUJER,1960-02-28,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,APS CONSULTORIO (CESFAM),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
3,118100,857926,MUJER,1933-01-12,CONCEPCION,CHIGUAYANTE,FONASA INSTITUCIONAL - (MAI) D,CONCEPCIÓN,"OTRAS INSTITUCIONES SALUD (CLÍNICAS PRIVADAS, ...",URGENCIA,...,113,0.090303,0,1,0.128118,882,113,3.717488,0.476277,0.117963
9,116110,900702,MUJER,1947-05-10,LINARES,PARRAL,FONASA INSTITUCIONAL - (MAI) B,DEL MAULE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,0,0.135324,1,0,0.0,102,0,2.309155,0.0,0.211155
11,118100,1260221,MUJER,1959-10-19,CONCEPCION,CORONEL,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,OTROS HOSPITALES DE LA RED,URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963
13,118100,1192972,MUJER,1993-12-29,CONCEPCION,CONCEPCION,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963

In [12]:
grd_femenino.shape

(154431, 52)

In [14]:
grd_femenino.columns  # Mostrar todas las columnas del DataFrame filtrado por sexo femenino

Index(['COD_ESTABLECIMIENTO', 'CIP_ENCRIPTADO', 'SEXO', 'FECHA_NACIMIENTO',
       'PROVINCIA', 'COMUNA_REGISTRADA', 'PREVISION', 'SERVICIO_SALUD',
       'TIPO_PROCEDENCIA', 'TIPO_INGRESO', 'FECHA_INGRESO', 'FECHAALTA',
       'TIPOALTA', 'DIAGNOSTICO1', 'DIAGNOSTICO2', 'DIAGNOSTICO3',
       'PROCEDIMIENTO1', 'PROCEDIMIENTO2', 'IR_29301_COD_GRD', 'IR_29301_PESO',
       'IR_29301_SEVERIDAD', 'IR_29301_MORTALIDAD', 'YEAR', 'EDAD',
       'DIAS_ESTANCIA', 'N_COMORBILIDADES', 'N_PROCEDIMIENTOS',
       'INDICE_CHARLSON', 'DESCRIPCION', 'SECCION', 'COD_REGION', 'REGION',
       'ESTABLECIMIENTO', 'COD_COMUNA', 'COMUNA_ESTAB', 'LATITUD', 'LONGITUD',
       'PRESTADOR', 'COMPLEJIDAD_ESTAB', 'POB_COMUNA', 'POB_REGION',
       'CAMAS_TOTALES', 'CAMAS_CRITICAS', 'POB_MULT_ESTAB',
       'COMUNA_CON_ESTAB_AC', 'FALLECIDO', 'CRITICAS_PROP', 'CAMAS_COMUNA',
       'CRITICAS_COMUNA', 'CAMAS_1000HAB', 'CRITICAS_1000HAB',
       'TASA_MORTALIDAD_COMUNA'],
      dtype='object')